name: CI/CD Docker Image to Docker Hub

on:
  push:
    branches:
      - main
      - staging # Trigger on pushes to main or staging
  pull_request:
    branches:
      - main
      - staging # Trigger on PRs to main or staging

jobs:
  build_and_push_staging:
    name: Build and Push Staging Docker Image
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push' # Only run on push to staging branch
    runs-on: ubuntu-latest
    environment: staging # Use the 'staging' GitHub Environment (for potential secrets or rules)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Assumes DOCKERHUB_USERNAME is a repo or staging env secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Assumes DOCKERHUB_TOKEN is a repo or staging env secret

      - name: Build and push Staging image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.staging # Use the staging Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:staging-latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:staging-${{ github.sha }}

  build_and_push_production:
    name: Build and Push Production Docker Image
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only run on push to main branch
    runs-on: ubuntu-latest
    environment: production # Use the 'production' GitHub Environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Assumes DOCKERHUB_USERNAME is a repo or production env secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Assumes DOCKERHUB_TOKEN is a repo or production env secret

      - name: Build and push Production image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.production # Use the production Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:${{ github.sha }}